ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'HEAD_TEACHER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'CLASS_TEACHER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'OFFICE_STAFF';

ALTER TABLE "users"
  ALTER COLUMN "role" SET DEFAULT 'OFFICE_STAFF';
